Repository 10up/distributor, pull requests merged in 2019-07, with the labels that each got.

#355 Refactor how we generate internal connection data
  includes/classes/InternalConnections/NetworkSiteConnection.php
Labels: enhancement

#420 Typo in variable name
  includes/classes/InternalConnections/NetworkSiteConnection.php
Labels: bug

#401 Define $local_post_types before the conditional to prevent PHP notice
  includes/utils.php
Labels: bug

#365 Lazy load available push connections
  .travis.yml
  assets/css/push.css
  assets/js/push.js
  includes/push-ui.php
  tests/wpacceptance/PushMenuTest.php
Labels: enhancement

#352 Update CONTRIBUTING.md clarifying release instructions
  CONTRIBUTING.md
Labels: Documentation

#415 add canonical URL distributing caveat
  README.md
Labels: Documentation

#371 Unify `dt_push_post_args` usage
  includes/classes/ExternalConnections/WordPressExternalConnection.php
Labels: Reporter Feedback, bug

#378 Adds extra parameters to dt_create_missing_terms.
  includes/utils.php
Labels: enhancement

#262 Fix duplication of terms
  includes/utils.php
  tests/php/UtilsTest.php
Labels: bug

#431 Make pull list table views include/exclude more performant
  assets/css/admin-pull-table.css
  includes/classes/PullListTable.php
Labels: bug

#406 Release version 1.5.0
  CHANGELOG.md
  distributor.php
  lang/distributor.pot
Labels: Documentation
