Repository 10up/distributor, pull requests merged in 2019-09, with the labels that each got.

#444 Fix/syndicated ext connections ui
  includes/push-ui.php
Labels: bug

#433 Add missing changelog links and dates
  CHANGELOG.md
Labels: Documentation

#448 Generate Hook Docs with a GitHub Action
  distributor.php
  hookdoc-conf.json
  includes/.github/workflows/build-docs.yml
  includes/classes/API/SubscriptionsController.php
  includes/classes/Authentication.php
  includes/classes/Authentications/WordPressBasicAuth.php
  includes/classes/Authentications/WordPressDotcomOauth2Authentication.php
  includes/classes/ExternalConnection.php
  includes/classes/ExternalConnections/WordPressExternalConnection.php
  includes/classes/InternalConnections/NetworkSiteConnection.php
  includes/classes/PullListTable.php
  includes/external-connection-cpt.php
  includes/pull-ui.php
  includes/push-ui.php
  includes/rest-api.php
  includes/subscriptions.php
  includes/syndicated-post-ui.php
  includes/template-tags.php
  includes/utils.php
  package-lock.json
  package.json
Labels: enhancement
