Repository 10up/distributor, pull requests merged in 2020-02, with the labels that each got.

#513 Group developer-related topics in readme.md
  README.md
Labels: Documentation

#450 Update all packages & build
  .babelrc
  assets/js/admin-external-connection.js
  assets/js/admin-pull.js
  assets/js/push.js
  gulp-tasks/cssclean.js
  gulp-tasks/csscomplete.js
  gulp-tasks/cssnano.js
  gulp-tasks/jsclean.js
  gulp-tasks/webpack.js
  gulpfile.babel.js
  package-lock.json
  package.json
  webpack.config.babel.js
Labels: dependencies

#514 Replace has_blocks with use_block_editor_for_post in is_using_gutenberg
  includes/utils.php
Labels: bug

#518 Run NetworkSiteConnection::update_syndicated on correct hook when using Gutenberg
  includes/classes/InternalConnections/NetworkSiteConnection.php
Labels: bug

#495 Select all feature added.
  assets/css/push.css
  assets/js/push.js
  includes/push-ui.php
Labels: enhancement

#519 Fix: REST API field are not getting populated correctly
  includes/rest-api.php
Labels: bug

#462 Clarify references to filters/hooks in README.md
  README.md
Labels: Documentation, enhancement

#525 Syntax issue on paragraph 75
  README.md
Labels: Documentation

#508 Add row action for pulling single post
  includes/classes/PullListTable.php
Labels: enhancement

#460 Adds JSON extension as a Composer requirement
  composer.json
  composer.lock
Labels: enhancement

#473 add `dt_syndicatable_capabilities` filter to push ui
  includes/push-ui.php
Labels: enhancement

#527 Use the original post author when pushing a network post
  includes/classes/InternalConnections/NetworkSiteConnection.php
Labels: bug
