Repository 10up/distributor, pull requests merged in 2020-07, with the labels that each got.

#598 fix images, remove gutenberg beta support, add caveat to README.md
  README.md
Labels: Documentation

#576 External connections page markup enhancements - #550
  includes/external-connection-cpt.php
Labels: enhancement

#564 Use WP native way of opening the Distributor menu
  assets/css/push.css
  assets/js/push.js
  includes/push-ui.php
Labels: enhancement

#607 Fix: unable to click on the view link using mouse
  assets/css/push.css
Labels: bug
