Repository 10up/distributor, pull requests merged in 2020-03, with the labels that each got.

#498 Fix/pull apply the content
  includes/classes/InternalConnections/NetworkSiteConnection.php
  includes/utils.php
Labels: bug

#532 Place pulled list action links in standard order
  includes/classes/PullListTable.php
Labels: enhancement

#529 Add filter for request timeout
  includes/subscriptions.php
Labels: enhancement

#544 add AppPwds caveat to external connections set up steps in README.md
  README.md
Labels: Documentation

#534 Fix: Block content pulled through external connections get converted to classic
  includes/classes/ExternalConnections/WordPressExternalConnection.php
  includes/utils.php
  tests/wpacceptance/SettingsTest.php
Labels: bug

#533 Added urldecode() to fix searching multiple words during a multisite pull
  includes/classes/InternalConnections/NetworkSiteConnection.php
  tests/wpacceptance/InternalPullTest.php
Labels: bug

#545 switch to building hookdocs on commits to master
  .github/workflows/build-docs.yml
Labels: Documentation

#542 Create readme.txt
  readme.txt
Labels: Documentation

#245 Fix timeout on ajax_verify_external_connection
  includes/classes/ExternalConnections/WordPressExternalConnection.php
  includes/rest-api.php
Labels: enhancement
