Repository 10up/distributor, pull requests merged in 2020-04, with the labels that each got.

#570 Fix: wrong permission route
  includes/classes/ExternalConnections/WordPressExternalConnection.php
  includes/rest-api.php
Labels: bug

#528 Docs: Unable to PUSH new CPTs
  README.md
Labels: Documentation

#543 Update Registration and Settings screen
  assets/css/admin-settings.css
  includes/settings.php
Labels: enhancement

#558 Change setting page title from h2 to h1.
  includes/settings.php
Labels: enhancement

#559 Fix password field label for attribute
  includes/classes/Authentications/WordPressBasicAuth.php
Labels: bug

#560 Tweak allowed to push markup
  assets/css/admin-external-connection.css
  includes/external-connection-cpt.php
Labels: enhancement

#562 Add label to Email and Registration Key fields.
  includes/settings.php
Labels: enhancement

#565 Use button in external connection URL.
  assets/js/admin-external-connection.js
Labels: enhancement

#566 Announce dynamic changes in external connection URL field
  assets/js/admin-external-connection.js
  includes/external-connection-cpt.php
Labels: enhancement

#571 Show 'View' link in push UI for external connections
  assets/js/push.js
  includes/push-ui.php
  tests/wpacceptance/PushMenuTest.php
Labels: enhancement

#574 Fix: Check for value of remote post id to verify push result
  includes/classes/ExternalConnections/WordPressExternalConnection.php
Labels: enhancement
