Repository 10up/distributor, pull requests merged in 2024-07, with the labels that each got.

#1243 Bump WordPress "tested up to" version 6.6
  readme.txt
Labels: needs:feedback

#1227 Fix strpos first arg null warning in php 8.1
  includes/settings.php
Labels: needs:code-review

#1228 Follow react rules of hooks
  assets/js/gutenberg-plugin.js
Labels: needs:code-review

#1247 fix/warning: Undefined array key "id"
  includes/classes/DistributorPost.php
Labels: needs:code-review

#1167 Check return value of get_post_meta
  includes/utils.php
Labels: needs:code-review

#1002 Added ability to view all post types when Pulling from an External Connection
  includes/classes/PullListTable.php
  includes/pull-ui.php
  includes/rest-api.php
Labels: needs:code-review, nice-to-have
